/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinteface;

import com.mycompany.projetoa3.Session;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import model.Produto;


public class DetalhesProduto extends javax.swing.JFrame {

    Produto produto;
    HomeV2 parentWindow;
    boolean noCarrinho = false;
    /**
     * Creates new form NewJFrame
     */
    public DetalhesProduto() {
        initComponents();
    }
    
    public DetalhesProduto(Produto produto, HomeV2 parentWindow) {
        initComponents();
        this.produto = produto;
        labelDescricao.setText(produto.getCategoria());
        labelNome.setText(produto.getDescricao());
        DecimalFormat df = new DecimalFormat("#,##0.00");
        labelPreco.setText("R$" + df.format(produto.getPreco()));
        this.parentWindow = parentWindow;
        
        int quantidadeSelecionada = Session.checarCarrinho(produto);
        int minQuantidade;
        if (quantidadeSelecionada > 0){
            noCarrinho = true;
            minQuantidade = 0;
            botaoComprar.setLabel("Atualizar");
        }else{
            minQuantidade = 1;
            quantidadeSelecionada = 1;
        }
        if (produto.getQtde_produto() == 1){
            labelDisponibilidade.setText("(1 disponível)");
            campoQuantidade.setModel(new SpinnerNumberModel(quantidadeSelecionada, minQuantidade, 1, 1));
        }else if(produto.getQtde_produto() == 0){
            botaoComprar.setEnabled(false);
            labelDisponibilidade.setText("Esgotado");
            campoQuantidade.setEnabled(false);
        }else{
            labelDisponibilidade.setText("(" + produto.getQtde_produto() + " disponíveis)");
            campoQuantidade.setModel(new SpinnerNumberModel(quantidadeSelecionada, minQuantidade, produto.getQtde_produto(), 1));
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        botaoComprar = new java.awt.Button();
        campoQuantidade = new javax.swing.JSpinner();
        labelPreco = new javax.swing.JLabel();
        labelDisponibilidade = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(207, 235, 252));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        labelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelDescricao.setText("Casual");
        labelDescricao.setToolTipText("");

        botaoComprar.setBackground(new java.awt.Color(32, 61, 146));
        botaoComprar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botaoComprar.setForeground(new java.awt.Color(255, 255, 255));
        botaoComprar.setLabel("Comprar");
        botaoComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoComprarActionPerformed(evt);
            }
        });

        labelPreco.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelPreco.setText("849,99");
        labelPreco.setToolTipText("");

        labelDisponibilidade.setText("(X disponíveis)");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nós apenas queremos dizer, \"HAVE A NIKE DAY.\" O brilho vive com o original do b-ball. Em homenagem aquelas coisas que não podemos viver sem, esta versão dos originais das quadras visa trazer o ar livre para dentro e vice-versa, e dá um novo toque ao que você conhece melhor: remetendo ao estilo dos anos 80.");
        jLabel2.setToolTipText("Nós apenas queremos dizer, \"HAVE A NIKE DAY.\" O brilho\nvive com o original do b-ball. Em homenagem aquelas\ncoisas que não podemos viver sem, esta versão dos\noriginais das quadras visa trazer o ar livre para dentro e\nvice-versa, e dá um novo toque ao que você conhece\nmelhor: remetendo ao estilo dos anos 80.");

        labelNome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelNome.setText("Nike Air Force");
        labelNome.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelNome)
                                        .addGap(99, 105, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPreco)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                            .addComponent(labelDisponibilidade, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelDescricao)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(labelDisponibilidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoComprarActionPerformed
        try {
            campoQuantidade.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(DetalhesProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (noCarrinho){
            Session.atualizarCarrinho(produto, (int)campoQuantidade.getValue());
            JOptionPane.showMessageDialog(null, "Carrinho atualizado");
            parentWindow.atualizaCarrinho();
            this.dispose();
        }else{
            if ((Integer)campoQuantidade.getValue() > 0){
                Session.adicionarAoCarrinho(produto, (int)campoQuantidade.getValue());
                JOptionPane.showMessageDialog(null, "Produto adicionado ao carrinho");
                parentWindow.atualizaCarrinho();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "escolha uma quantidade");
            }
        }
        
    }//GEN-LAST:event_botaoComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button botaoComprar;
    private javax.swing.JSpinner campoQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelDisponibilidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPreco;
    // End of variables declaration//GEN-END:variables
}
