/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinteface;

import dao.ProdutoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.Produto;

/**
 *
 * @author gvj20
 */
public class HomeV2 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeV2() {
        initComponents();
        carregaProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane2 = new javax.swing.JTabbedPane();
        painelHome = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        painelMasculino = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        painelMasculinoCenter = new javax.swing.JPanel();
        painelFeminino = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        painelFemininoCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        painelHome.setBackground(new java.awt.Color(0, 102, 102));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelHomeLayout = new javax.swing.GroupLayout(painelHome);
        painelHome.setLayout(painelHomeLayout);
        painelHomeLayout.setHorizontalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelHomeLayout.setVerticalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", painelHome);

        painelMasculino.setBackground(new java.awt.Color(0, 102, 102));
        painelMasculino.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Os melhores");
        jLabel1.setToolTipText("");
        painelMasculino.add(jLabel1, java.awt.BorderLayout.NORTH);

        painelMasculinoCenter.setOpaque(false);
        painelMasculinoCenter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 12));
        painelMasculino.add(painelMasculinoCenter, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Masculino", painelMasculino);

        painelFeminino.setBackground(new java.awt.Color(0, 102, 102));
        painelFeminino.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setText("Os melhores");
        jLabel2.setToolTipText("");
        painelFeminino.add(jLabel2, java.awt.BorderLayout.NORTH);

        painelFemininoCenter.setOpaque(false);
        painelFemininoCenter.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 12, 12));
        painelFeminino.add(painelFemininoCenter, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Feminino", painelFeminino);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        setSize(new java.awt.Dimension(849, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel painelFeminino;
    private javax.swing.JPanel painelFemininoCenter;
    private javax.swing.JPanel painelHome;
    private javax.swing.JPanel painelMasculino;
    private javax.swing.JPanel painelMasculinoCenter;
    // End of variables declaration//GEN-END:variables


    private void carregaProdutos(){
        try {
            ProdutoDAO produtoDao = new ProdutoDAO();
            for (Produto produto: produtoDao.findAllProduto()){
                addProduto(produto);
            }
            produtoDao.Close();
        } catch (SQLException ex) {
            Logger.getLogger(HomeV2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void addProduto(Produto produto){
        java.awt.GridBagConstraints gridBagConstraints;
        JPanel painelProtudo = new JPanel();
        painelProtudo.setBackground(java.awt.Color.gray);
        painelProtudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 51), 3, true));
        painelProtudo.setForeground(java.awt.Color.white);
        painelProtudo.setMaximumSize(getPreferredSize());
        painelProtudo.setMinimumSize(getPreferredSize());
        painelProtudo.setPreferredSize(new java.awt.Dimension(250, 375));
        painelProtudo.setLayout(new java.awt.GridBagLayout());

        JPanel painelImagemProduto = new JPanel();
        painelImagemProduto.setBackground(new java.awt.Color(204, 255, 204));
        painelImagemProduto.setMaximumSize(new java.awt.Dimension(200, 300));
        painelImagemProduto.setMinimumSize(new java.awt.Dimension(200, 300));
        painelImagemProduto.setName(""); // NOI18N
        painelImagemProduto.setPreferredSize(new java.awt.Dimension(200, 300));

        javax.swing.GroupLayout painelImagemProdutoLayout = new javax.swing.GroupLayout(painelImagemProduto);
        painelImagemProduto.setLayout(painelImagemProdutoLayout);
        painelImagemProdutoLayout.setHorizontalGroup(
            painelImagemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        painelImagemProdutoLayout.setVerticalGroup(
            painelImagemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelProtudo.add(painelImagemProduto, new java.awt.GridBagConstraints());

        JLabel labelNomeProduto = new JLabel();
        labelNomeProduto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        labelNomeProduto.setText(produto.getDescricao() + " R$ " + produto.getPreco());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        painelProtudo.add(labelNomeProduto, gridBagConstraints);

        JButton botaoComprarProduto = new JButton();
        botaoComprarProduto.setBackground(new java.awt.Color(255, 255, 255));
        botaoComprarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoComprarProduto.setForeground(new java.awt.Color(0, 0, 0));
        botaoComprarProduto.setText("Comprar");
        botaoComprarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarAoCarrinho(produto);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        painelProtudo.add(botaoComprarProduto, gridBagConstraints);
        
        if (produto.getCategoria().equals("masculino"))
            painelMasculinoCenter.add(painelProtudo);
        else if (produto.getCategoria().equals("feminino"))
            painelFemininoCenter.add(painelProtudo);
        else
            System.out.println("Produto sem categoria");
        
        

    }
    
    private void adicionarAoCarrinho(Produto produto){
        System.out.println("Item " + produto.getDescricao() + " adicionado ao carrinho");
    }
}
