/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinteface;

import com.mycompany.projetoa3.Session;
import dados.relatorios.DadosRelatorioCliente;
import dados.relatorios.DadosRelatorioEstado;
import dao.CompraDAO;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Compra;

/**
 *
 * @author renat
 */
public class ManterVendas extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendas
     */
    public ManterVendas() {
        initComponents();
        carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelTodas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        boxProcurar = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        labelNumero = new javax.swing.JLabel();
        labelNF = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boxEstado = new javax.swing.JComboBox<>();
        botaoMudar = new javax.swing.JButton();
        painelClientes = new javax.swing.JPanel();
        jpanel = new javax.swing.JScrollPane();
        tabelaVendasPorCliente = new javax.swing.JTable();
        header1 = new javax.swing.JPanel();
        campoCPF = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boxProcurarPorCliente = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        labelNumero1 = new javax.swing.JLabel();
        labelNF1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxEstado1 = new javax.swing.JComboBox<>();
        botaoMudar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setSize(new java.awt.Dimension(600, 400));

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        painelTodas.setLayout(new java.awt.BorderLayout());

        tabelaVendas.setBackground(new java.awt.Color(207, 235, 252));
        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Data", "Cliente", "Valor Total", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaVendas);
        if (tabelaVendas.getColumnModel().getColumnCount() > 0) {
            tabelaVendas.getColumnModel().getColumn(4).setHeaderValue("Estado");
        }

        painelTodas.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        header.setBackground(new java.awt.Color(0, 102, 153));
        header.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mostrar: ");
        header.add(jLabel1);

        boxProcurar.setBackground(new java.awt.Color(255, 255, 255));
        boxProcurar.setForeground(new java.awt.Color(0, 0, 0));
        boxProcurar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Não Canceladas", "Processamento", "Finalizada", "Cancelada", "" }));
        boxProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProcurarActionPerformed(evt);
            }
        });
        header.add(boxProcurar);

        painelTodas.add(header, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 15);
        flowLayout1.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout1);

        labelNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero.setText("NF:");
        jPanel2.add(labelNumero);

        labelNF.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(labelNF);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mudar estado");
        jPanel2.add(jLabel4);

        boxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processando", "Finalizada", "Cancelada" }));
        jPanel2.add(boxEstado);

        botaoMudar.setText("Mudar");
        botaoMudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudarActionPerformed(evt);
            }
        });
        jPanel2.add(botaoMudar);

        painelTodas.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Todas", painelTodas);

        painelClientes.setLayout(new java.awt.BorderLayout());

        tabelaVendasPorCliente.setBackground(new java.awt.Color(255, 255, 255));
        tabelaVendasPorCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Data", "CPF", "Valor Total", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendasPorCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaVendasPorClienteMouseClicked(evt);
            }
        });
        jpanel.setViewportView(tabelaVendasPorCliente);

        painelClientes.add(jpanel, java.awt.BorderLayout.CENTER);

        header1.setBackground(new java.awt.Color(0, 102, 153));
        header1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPF.setMinimumSize(new java.awt.Dimension(160, 22));
        campoCPF.setPreferredSize(new java.awt.Dimension(90, 22));
        header1.add(campoCPF);

        jButton1.setText("Procurar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        header1.add(jButton1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mostrar: ");
        header1.add(jLabel2);

        boxProcurarPorCliente.setBackground(new java.awt.Color(255, 255, 255));
        boxProcurarPorCliente.setForeground(new java.awt.Color(0, 0, 0));
        boxProcurarPorCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Processamento", "Finalizada", "Canceladas", "" }));
        boxProcurarPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProcurarPorClienteActionPerformed(evt);
            }
        });
        header1.add(boxProcurarPorCliente);

        painelClientes.add(header1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(51, 0, 51));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 15, 15);
        flowLayout2.setAlignOnBaseline(true);
        jPanel3.setLayout(flowLayout2);

        labelNumero1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNumero1.setForeground(new java.awt.Color(255, 255, 255));
        labelNumero1.setText("NF:");
        jPanel3.add(labelNumero1);

        labelNF1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(labelNF1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mudar estado");
        jPanel3.add(jLabel5);

        boxEstado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Processando", "Finalizada", "Cancelada" }));
        jPanel3.add(boxEstado1);

        botaoMudar1.setText("Mudar");
        botaoMudar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMudar1ActionPerformed(evt);
            }
        });
        jPanel3.add(botaoMudar1);

        painelClientes.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Por CPF", painelClientes);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProcurarActionPerformed
        carregarVendas();
    }//GEN-LAST:event_boxProcurarActionPerformed

    private void boxProcurarPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProcurarPorClienteActionPerformed
        carregarVendasPorCliente();
    }//GEN-LAST:event_boxProcurarPorClienteActionPerformed

    private void tabelaVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendasMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel)tabelaVendas.getModel();
        int selectedRow = tabelaVendas.getSelectedRow();
        labelNF.setText(tableModel.getValueAt(selectedRow, 0).toString());
        if (tableModel.getValueAt(selectedRow, 4).equals("Processando")) {
            boxEstado.setSelectedIndex(0);
        }else if (tableModel.getValueAt(selectedRow, 4).equals("Finalizada")){
            boxEstado.setSelectedIndex(1);
        }else{
            boxEstado.setSelectedIndex(2);
        }
      
        
        botaoMudar.setEnabled(true);

    }//GEN-LAST:event_tabelaVendasMouseClicked

    private void botaoMudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudarActionPerformed
        try {
            CompraDAO compraDAO = new CompraDAO();
            if (compraDAO.updateCompraEstado(Integer.parseInt(labelNF.getText()), boxEstado.getSelectedItem()+"")){
                JOptionPane.showMessageDialog(null, "Estado atualizado");
                carregarVendas();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManterVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_botaoMudarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        carregarVendasPorCliente();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoMudar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMudar1ActionPerformed
        try {
            CompraDAO compraDAO = new CompraDAO();
            if (compraDAO.updateCompraEstado(Integer.parseInt(labelNF1.getText()), boxEstado1.getSelectedItem()+"")){
                JOptionPane.showMessageDialog(null, "Estado atualizado");
                carregarVendasPorCliente();
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManterVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoMudar1ActionPerformed

    private void tabelaVendasPorClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaVendasPorClienteMouseClicked
        DefaultTableModel tableModel = (DefaultTableModel)tabelaVendasPorCliente.getModel();
        int selectedRow = tabelaVendasPorCliente.getSelectedRow();
        labelNF1.setText(tableModel.getValueAt(selectedRow, 0).toString());
        if (tableModel.getValueAt(selectedRow, 4).equals("Processando")) {
            boxEstado1.setSelectedIndex(0);
        }else if (tableModel.getValueAt(selectedRow, 4).equals("Finalizada")){
            boxEstado1.setSelectedIndex(1);
        }else{
            boxEstado1.setSelectedIndex(2);
        }
      
        
        botaoMudar1.setEnabled(true);
    }//GEN-LAST:event_tabelaVendasPorClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMudar;
    private javax.swing.JButton botaoMudar1;
    private javax.swing.JComboBox<String> boxEstado;
    private javax.swing.JComboBox<String> boxEstado1;
    private javax.swing.JComboBox<String> boxProcurar;
    private javax.swing.JComboBox<String> boxProcurarPorCliente;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JPanel header;
    private javax.swing.JPanel header1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane jpanel;
    private javax.swing.JLabel labelNF;
    private javax.swing.JLabel labelNF1;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelNumero1;
    private javax.swing.JPanel painelClientes;
    private javax.swing.JPanel painelTodas;
    private javax.swing.JTable tabelaVendas;
    private javax.swing.JTable tabelaVendasPorCliente;
    // End of variables declaration//GEN-END:variables

    private void carregarDados() {
        carregarVendas();
    }
    private void carregarVendas(){
        ((DefaultTableModel)tabelaVendas.getModel()).setRowCount(0);
        try {
            CompraDAO compraDAO = new CompraDAO();
            List<Compra> compras = new ArrayList<>();
            switch (boxProcurar.getSelectedIndex()) {
                case 1:
                    compras = compraDAO.findAllNaoCancelada();
                    break;
                case 2:
                    compras = compraDAO.findAllCompra("Processando");
                    break;
                case 3:
                    compras = compraDAO.findAllCompra("Finalizada");
                    break;
                case 4:
                    compras = compraDAO.findAllCompra("Cancelada");
                    break;
                default:
                    compras = compraDAO.findAllCompra();;
            }

            
            
            DefaultTableModel tableModel = (DefaultTableModel)tabelaVendas.getModel();
            double totalFinal = 0.0;
            DecimalFormat df = new DecimalFormat("#,###.##");
            for (Compra compra:compras){
                tableModel.addRow(new Object[]{compra.getNotaFiscal(), compra.getDataCompra(), compra.getCliente().getNome(), "R$"+df.format(compra.getValorTotal()), compra.getEstado()});
                totalFinal += compra.getValorTotal();
            }
           
                
            compraDAO.close();
        } catch (SQLException ex) {
            Logger.getLogger(ManterVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void carregarVendasPorCliente(){
        ((DefaultTableModel)tabelaVendasPorCliente.getModel()).setRowCount(0);
        try {
            CompraDAO compraDAO = new CompraDAO();
            List<Compra> compras = new ArrayList<>();
            switch (boxProcurarPorCliente.getSelectedIndex()) {
                case 1:
                    compras = compraDAO.findCompraByCpf(campoCPF.getText(), "Processando");
                    break;
                case 2:
                    compras = compraDAO.findCompraByCpf(campoCPF.getText(), "Finalizada");
                    break;
                case 3:
                    compras = compraDAO.findCompraByCpf(campoCPF.getText(), "Cancelada");
                    break;
                default:
                    compras = compraDAO.findCompraByCpf(campoCPF.getText(), "");
            }

            DefaultTableModel tableModel = (DefaultTableModel)tabelaVendasPorCliente.getModel();

            DecimalFormat df = new DecimalFormat("#,###.##");
            for (Compra compra:compras){
                tableModel.addRow(new Object[]{compra.getNotaFiscal(), compra.getDataCompra(), compra.getCliente().getNome(), "R$"+df.format(compra.getValorTotal()), compra.getEstado()});
            }
            

            compraDAO.close();
        } catch (SQLException ex) {
            Logger.getLogger(ManterVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
